package view;

import control.CategoriaControl;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class CategoriaVIEW extends javax.swing.JFrame {

    public CategoriaVIEW() {

        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTCategorias.getModel();
        jTCategorias.setRowSorter(new TableRowSorter(modelo));
        jTCategorias.setBorder(BorderFactory.createBevelBorder(0));
        jTCategorias.getTableHeader().setBorder(BorderFactory.createBevelBorder(0));

        Criar_ler_tabela();

        jLid.setVisible(false);
        jTextField_id.setVisible(false);
        jBalterar.setVisible(false);
        jBexcluir.setVisible(false);

    }

    public void Criar_ler_tabela() {

        DefaultTableModel modelo = (DefaultTableModel) jTCategorias.getModel();
        modelo.setNumRows(0);

        ArrayList<String> tabela = new ArrayList<>();
        CategoriaControl cc = new CategoriaControl();

        cc.receber_tabela(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        brNova_Categoria = new javax.swing.JButton();
        jBexcluir_categoria = new javax.swing.JButton();
        jBeditar_categoria = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCategorias = new javax.swing.JTable();
        jLnome = new javax.swing.JLabel();
        jLid = new javax.swing.JLabel();
        jTextField_categoria = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jBsalvar = new keeptoo.KButton();
        jBalterar = new keeptoo.KButton();
        jBexcluir = new keeptoo.KButton();
        aviso1 = new javax.swing.JLabel();
        aviso2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        kGradientPanel3.setkEndColor(new java.awt.Color(102, 255, 153));
        kGradientPanel3.setkGradientFocus(200);
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 51, 255));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart.png"))); // NOI18N
        kGradientPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        brNova_Categoria.setBackground(new java.awt.Color(153, 51, 255));
        brNova_Categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brNova_Categoria.setForeground(new java.awt.Color(255, 255, 255));
        brNova_Categoria.setText("Nova categoria");
        brNova_Categoria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        brNova_Categoria.setContentAreaFilled(false);
        brNova_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brNova_CategoriaActionPerformed(evt);
            }
        });
        kGradientPanel3.add(brNova_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 42));

        jBexcluir_categoria.setBackground(new java.awt.Color(153, 51, 255));
        jBexcluir_categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBexcluir_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jBexcluir_categoria.setText("Excluir categoria");
        jBexcluir_categoria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jBexcluir_categoria.setContentAreaFilled(false);
        jBexcluir_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluir_categoriaActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jBexcluir_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, 42));

        jBeditar_categoria.setBackground(new java.awt.Color(153, 51, 255));
        jBeditar_categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBeditar_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jBeditar_categoria.setText("Editar categoria");
        jBeditar_categoria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jBeditar_categoria.setContentAreaFilled(false);
        jBeditar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditar_categoriaActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jBeditar_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 44));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/left-arrow.png"))); // NOI18N
        jButton3.setText("Voltar");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 51, 255));

        jTCategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Categorias", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCategorias.setGridColor(new java.awt.Color(255, 255, 255));
        jTCategorias.setOpaque(false);
        jTCategorias.setShowHorizontalLines(false);
        jTCategorias.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTCategorias);

        jLnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLnome.setForeground(new java.awt.Color(153, 51, 255));
        jLnome.setText("Nome:");

        jLid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLid.setForeground(new java.awt.Color(153, 51, 255));
        jLid.setText("Id:");

        jTextField_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_categoria.setForeground(new java.awt.Color(102, 51, 255));
        jTextField_categoria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));

        jTextField_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_id.setForeground(new java.awt.Color(102, 51, 255));
        jTextField_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 153, 255)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBsalvar.setText("Salvar");
        jBsalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBsalvar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        jBsalvar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        jBsalvar.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        jBsalvar.setkIndicatorColor(new java.awt.Color(0, 204, 153));
        jBsalvar.setkSelectedColor(new java.awt.Color(0, 204, 153));
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBalterar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        jBalterar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        jBalterar.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        jBalterar.setkIndicatorColor(new java.awt.Color(0, 204, 153));
        jBalterar.setkSelectedColor(new java.awt.Color(0, 204, 153));
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBexcluir.setText("Excluir");
        jBexcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBexcluir.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        jBexcluir.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        jBexcluir.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        jBexcluir.setkIndicatorColor(new java.awt.Color(0, 204, 153));
        jBexcluir.setkSelectedColor(new java.awt.Color(0, 204, 153));
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        aviso1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aviso1.setForeground(new java.awt.Color(255, 0, 51));

        aviso2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aviso2.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aviso1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(aviso2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLnome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aviso1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aviso2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBeditar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditar_categoriaActionPerformed

        jLnome.setVisible(true);
        jTextField_categoria.setVisible(true);

        jBsalvar.setVisible(false);

        jLid.setVisible(true);
        jTextField_id.setVisible(true);
        jBalterar.setVisible(true);
        jBexcluir.setVisible(false);

    }//GEN-LAST:event_jBeditar_categoriaActionPerformed

    private void brNova_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brNova_CategoriaActionPerformed

        jLnome.setVisible(true);
        jBsalvar.setVisible(true);
        jTextField_categoria.setVisible(true);

        jLid.setVisible(false);
        jTextField_id.setVisible(false);
        jBalterar.setVisible(false);
        jBexcluir.setVisible(false);

    }//GEN-LAST:event_brNova_CategoriaActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        aviso1.setText("");
        aviso2.setText("");
        CategoriaControl ct = new CategoriaControl();
        if (jTextField_categoria.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso1.setText("O Campo 'categoria' esta em branco");

        } else {
            ArrayList<String> myArrayList = new ArrayList<>();
            myArrayList.add(jTextField_categoria.getText());

            ct.recebe_lista_salva(myArrayList);

            Criar_ler_tabela();

        }


    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed

        aviso1.setText("");
        aviso2.setText("");
        CategoriaControl ct = new CategoriaControl();
        if (jTextField_categoria.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso1.setText("O Campo 'categoria' esta em branco");

        } else if (jTextField_id.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso2.setText("O Campo 'id' esta em branco");

        } else if (ct.ValidaNumero(jTextField_id) == true) {

            ArrayList<String> myArrayList = new ArrayList<>();
            myArrayList.add(jTextField_id.getText());
            myArrayList.add(jTextField_categoria.getText());

            ct.recebe_lista_altera(myArrayList);

            Criar_ler_tabela();

        }


    }//GEN-LAST:event_jBalterarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new AdminVIEW().setVisible(true);//que quer abrir
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBexcluir_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluir_categoriaActionPerformed
        // TODO add your handling code here:

        jLnome.setVisible(false);
        jBsalvar.setVisible(false);
        jTextField_categoria.setVisible(false);

        jLid.setVisible(true);
        jTextField_id.setVisible(true);
        jBalterar.setVisible(false);
        jBexcluir.setVisible(true);


    }//GEN-LAST:event_jBexcluir_categoriaActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        aviso2.setText("");
        CategoriaControl ct = new CategoriaControl();
        if (jTextField_id.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso2.setText("O Campo 'id' esta em branco");

        } else if (ct.ValidaNumero(jTextField_id) == true) {
            ArrayList<String> myArrayList = new ArrayList<>();
            myArrayList.add(jTextField_id.getText());

            ct.recebe_lista_exclui(myArrayList);

            Criar_ler_tabela();

        }

    }//GEN-LAST:event_jBexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new CategoriaVIEW().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso1;
    private javax.swing.JLabel aviso2;
    private javax.swing.JButton brNova_Categoria;
    private keeptoo.KButton jBalterar;
    private javax.swing.JButton jBeditar_categoria;
    private keeptoo.KButton jBexcluir;
    private javax.swing.JButton jBexcluir_categoria;
    private keeptoo.KButton jBsalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLnome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCategorias;
    private javax.swing.JTextField jTextField_categoria;
    private javax.swing.JTextField jTextField_id;
    private keeptoo.KGradientPanel kGradientPanel3;
    // End of variables declaration//GEN-END:variables
}
