/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ProdutosControl;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dionatan
 */
public class ProdutoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form LoginVIEW
     */
    public ProdutoVIEW() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTtabelaProdutos.getModel();
        jTtabelaProdutos.setRowSorter(new TableRowSorter(modelo));
        jTtabelaProdutos.setBorder(BorderFactory.createBevelBorder(0));
        jTtabelaProdutos.getTableHeader().setBorder(BorderFactory.createBevelBorder(0));

        Criar_ler_tabela();

        jLabelcategoria.setVisible(true);
        jLabelpreco.setVisible(true);
        jTpreco.setVisible(true);
        kButtonsalvar.setVisible(true);

        jLabelid.setVisible(false);
        jtid.setVisible(false);
        kButtonexcluir.setVisible(false);
        kButtonalterar.setVisible(false);
    }

    public void Criar_ler_tabela() {

        DefaultTableModel modelo = (DefaultTableModel) jTtabelaProdutos.getModel();
        modelo.setNumRows(0);

        ArrayList<String> tabela = new ArrayList<>();
        ProdutosControl pc = new ProdutosControl();

        pc.receber_tabela(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        brNova_produto = new javax.swing.JButton();
        jBeditar_produto = new javax.swing.JButton();
        jBexcluir_produto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelpreco = new javax.swing.JLabel();
        jTpreco = new javax.swing.JTextField();
        jLabelcategoria = new javax.swing.JLabel();
        jtcategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtabelaProdutos = new javax.swing.JTable();
        jLabelid = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();
        kButtonsalvar = new keeptoo.KButton();
        kButtonalterar = new keeptoo.KButton();
        kButtonexcluir = new keeptoo.KButton();
        aviso1 = new javax.swing.JLabel();
        aviso2 = new javax.swing.JLabel();
        aviso4 = new javax.swing.JLabel();
        aviso3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 153));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 51, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart.png"))); // NOI18N

        brNova_produto.setBackground(new java.awt.Color(153, 51, 255));
        brNova_produto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brNova_produto.setForeground(new java.awt.Color(255, 255, 255));
        brNova_produto.setText("Nova produto");
        brNova_produto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        brNova_produto.setContentAreaFilled(false);
        brNova_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brNova_produtoActionPerformed(evt);
            }
        });

        jBeditar_produto.setBackground(new java.awt.Color(153, 51, 255));
        jBeditar_produto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBeditar_produto.setForeground(new java.awt.Color(255, 255, 255));
        jBeditar_produto.setText("Editar produto");
        jBeditar_produto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jBeditar_produto.setContentAreaFilled(false);
        jBeditar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditar_produtoActionPerformed(evt);
            }
        });

        jBexcluir_produto.setBackground(new java.awt.Color(153, 51, 255));
        jBexcluir_produto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBexcluir_produto.setForeground(new java.awt.Color(255, 255, 255));
        jBexcluir_produto.setText("Exluir Produto");
        jBexcluir_produto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jBexcluir_produto.setContentAreaFilled(false);
        jBexcluir_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluir_produtoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/left-arrow.png"))); // NOI18N
        jButton3.setText("Voltar");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(brNova_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBexcluir_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBeditar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(79, 79, 79))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(brNova_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jBeditar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addComponent(jBexcluir_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLnome.setForeground(new java.awt.Color(99, 15, 229));
        jLnome.setText("Nome:");
        jPanel1.add(jLnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 23, -1, -1));

        jtnome.setForeground(new java.awt.Color(99, 15, 229));
        jtnome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(99, 15, 229)));
        jtnome.setOpaque(false);
        jtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnomeActionPerformed(evt);
            }
        });
        jPanel1.add(jtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 26, 270, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 0, 26, -1));

        jLabelpreco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelpreco.setForeground(new java.awt.Color(99, 15, 229));
        jLabelpreco.setText("Preço:");
        jPanel1.add(jLabelpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 23, -1, -1));

        jTpreco.setForeground(new java.awt.Color(99, 15, 229));
        jTpreco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(99, 15, 229)));
        jTpreco.setOpaque(false);
        jTpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTprecoActionPerformed(evt);
            }
        });
        jPanel1.add(jTpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 26, 79, 20));

        jLabelcategoria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelcategoria.setForeground(new java.awt.Color(99, 15, 229));
        jLabelcategoria.setText("Categoria:");
        jPanel1.add(jLabelcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtcategoria.setForeground(new java.awt.Color(99, 15, 229));
        jtcategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(99, 15, 229)));
        jtcategoria.setOpaque(false);
        jtcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, 20));

        jTtabelaProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTtabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Categoria", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtabelaProdutos.setGridColor(new java.awt.Color(255, 255, 255));
        jTtabelaProdutos.setOpaque(false);
        jTtabelaProdutos.setShowHorizontalLines(false);
        jTtabelaProdutos.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTtabelaProdutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 490, 250));

        jLabelid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelid.setForeground(new java.awt.Color(99, 15, 229));
        jLabelid.setText("i:d referente ao produto:");
        jPanel1.add(jLabelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jtid.setForeground(new java.awt.Color(99, 15, 229));
        jtid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(99, 15, 229)));
        jtid.setOpaque(false);
        jtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidActionPerformed(evt);
            }
        });
        jPanel1.add(jtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 47, 20));

        kButtonsalvar.setText("Salvar");
        kButtonsalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButtonsalvar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButtonsalvar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButtonsalvar.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        kButtonsalvar.setkIndicatorColor(new java.awt.Color(0, 204, 153));
        kButtonsalvar.setkSelectedColor(new java.awt.Color(0, 204, 153));
        kButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(kButtonsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 64, 34));

        kButtonalterar.setText("alterar");
        kButtonalterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButtonalterar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButtonalterar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButtonalterar.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        kButtonalterar.setkIndicatorColor(new java.awt.Color(0, 204, 153));
        kButtonalterar.setkSelectedColor(new java.awt.Color(0, 204, 153));
        kButtonalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonalterarActionPerformed(evt);
            }
        });
        jPanel1.add(kButtonalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 64, 34));

        kButtonexcluir.setText("Excluir");
        kButtonexcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButtonexcluir.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButtonexcluir.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButtonexcluir.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        kButtonexcluir.setkIndicatorColor(new java.awt.Color(0, 204, 153));
        kButtonexcluir.setkSelectedColor(new java.awt.Color(0, 204, 153));
        kButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonexcluirActionPerformed(evt);
            }
        });
        jPanel1.add(kButtonexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 64, 34));

        aviso1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aviso1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(aviso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 250, 20));

        aviso2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aviso2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(aviso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 250, 20));

        aviso4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aviso4.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(aviso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 20));

        aviso3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aviso3.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(aviso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTprecoActionPerformed

    private void jtcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcategoriaActionPerformed

    private void brNova_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brNova_produtoActionPerformed

        jLnome.setVisible(true);
        jtnome.setVisible(true);
        jtcategoria.setVisible(true);
        jLabelcategoria.setVisible(true);
        jLabelpreco.setVisible(true);
        jTpreco.setVisible(true);
        kButtonsalvar.setVisible(true);

        jLabelid.setVisible(false);
        jtid.setVisible(false);
        kButtonexcluir.setVisible(false);
        kButtonalterar.setVisible(false);

    }//GEN-LAST:event_brNova_produtoActionPerformed

    private void jBeditar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditar_produtoActionPerformed

        jtcategoria.setVisible(true);
        jLnome.setVisible(true);
        jtnome.setVisible(true);
        jLabelid.setVisible(true);
        jtid.setVisible(true);
        jLabelcategoria.setVisible(true);
        jLabelpreco.setVisible(true);
        jTpreco.setVisible(true);
        kButtonsalvar.setVisible(false);
        kButtonexcluir.setVisible(false);
        kButtonalterar.setVisible(true);

    }//GEN-LAST:event_jBeditar_produtoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new AdminVIEW().setVisible(true);//que quer abrir
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBexcluir_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluir_produtoActionPerformed

        jLnome.setVisible(false);
        jtnome.setVisible(false);
        jtcategoria.setVisible(false);
        jLabelid.setVisible(true);
        jtid.setVisible(true);
        jLabelcategoria.setVisible(false);
        jLabelpreco.setVisible(false);
        jTpreco.setVisible(false);
        kButtonsalvar.setVisible(false);
        kButtonexcluir.setVisible(true);
        kButtonalterar.setVisible(false);
    }//GEN-LAST:event_jBexcluir_produtoActionPerformed

    private void jtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidActionPerformed

    }//GEN-LAST:event_jtidActionPerformed

    private void kButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonsalvarActionPerformed
        ProdutosControl pc = new ProdutosControl();
        aviso1.setText("");
        aviso2.setText("");
        aviso3.setText("");
        if (jtnome.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso2.setText("O Campo 'nome' esta em branco");

        } else if (jtcategoria.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso3.setText("O Campo 'categoria' esta em branco");

        } else if (jTpreco.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso1.setText("O Campo 'preço' esta em branco");

        } else {
            if (pc.ValidaNumero(jTpreco) == true) {
                if (pc.ValidaNumero(jtcategoria) == true) {
                    ArrayList<String> myArrayList = new ArrayList<>();

                    myArrayList.add(jtnome.getText());
                    myArrayList.add(jTpreco.getText());
                    myArrayList.add(jtcategoria.getText());

                    pc.recebe_lista_salva(myArrayList);

                    Criar_ler_tabela();
                } else {
                    JOptionPane.showMessageDialog(null, "Campo categoria só aceita números", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Campo preço só aceita números", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_kButtonsalvarActionPerformed

    private void kButtonalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonalterarActionPerformed

        ProdutosControl pc = new ProdutosControl();
        aviso1.setText("");
        aviso2.setText("");
        aviso3.setText("");
        aviso4.setText("");
        if (jtnome.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso2.setText("O Campo 'nome' esta em branco");

        } else if (jtcategoria.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso3.setText("O Campo 'categoria' esta em branco");

        } else if (jTpreco.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso1.setText("O Campo 'preço' esta em branco");

        } else if (jtid.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso4.setText("O Campo 'id referente ao produto' esta em branco");

        } else {
            if (pc.ValidaNumero(jtid) == true) {
                if (pc.ValidaNumero(jTpreco) == true) {
                    if (pc.ValidaNumero(jtcategoria) == true) {
                        ArrayList<String> myArrayList = new ArrayList<>();
                        myArrayList.add(jtid.getText());
                        myArrayList.add(jtnome.getText());
                        myArrayList.add(jTpreco.getText());
                        myArrayList.add(jtcategoria.getText());

                        pc.recebe_lista_altera(myArrayList);

                        Criar_ler_tabela();
                    } else {
                        JOptionPane.showMessageDialog(null, "Campo categoria só aceita números", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Campo preço só aceita números", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Campo id referente ao produto só aceita números", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_kButtonalterarActionPerformed

    private void kButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonexcluirActionPerformed
        ProdutosControl pc = new ProdutosControl();

        aviso4.setText("");
        if (jtid.getText().trim().isEmpty()) {
            //instrucao para campo vazio
            aviso3.setText("O Campo 'id referente ao produto' esta em branco");

        } else {
            if (pc.ValidaNumero(jtid) == true) {
                ArrayList<String> myArrayList = new ArrayList<>();
                myArrayList.add(jtid.getText());

                pc.recebe_lista_exclui(myArrayList);

                Criar_ler_tabela();
            } else {
                JOptionPane.showMessageDialog(null, "Campo id referente ao produto só aceita números", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_kButtonexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso1;
    private javax.swing.JLabel aviso2;
    private javax.swing.JLabel aviso3;
    private javax.swing.JLabel aviso4;
    private javax.swing.JButton brNova_produto;
    private javax.swing.JButton jBeditar_produto;
    private javax.swing.JButton jBexcluir_produto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelcategoria;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelpreco;
    private javax.swing.JLabel jLnome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTpreco;
    private javax.swing.JTable jTtabelaProdutos;
    private javax.swing.JTextField jtcategoria;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtnome;
    private keeptoo.KButton kButtonalterar;
    private keeptoo.KButton kButtonexcluir;
    private keeptoo.KButton kButtonsalvar;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
